- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: mywebansible
      image: "xox1019/mywebansible:latest"
      state: started
      ports:
      - "80:8080"
